/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IndicatorsRouteImport } from './routes/indicators'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as IndicatorIdRouteImport } from './routes/indicator.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicatorsRoute = IndicatorsRouteImport.update({
  id: '/indicators',
  path: '/indicators',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicatorIdRoute = IndicatorIdRouteImport.update({
  id: '/indicator/$id',
  path: '/indicator/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/indicators': typeof IndicatorsRoute
  '/methodology': typeof MethodologyRoute
  '/indicator/$id': typeof IndicatorIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/indicators': typeof IndicatorsRoute
  '/methodology': typeof MethodologyRoute
  '/indicator/$id': typeof IndicatorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/indicators': typeof IndicatorsRoute
  '/methodology': typeof MethodologyRoute
  '/indicator/$id': typeof IndicatorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/indicators' | '/methodology' | '/indicator/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/indicators' | '/methodology' | '/indicator/$id'
  id: '__root__' | '/' | '/indicators' | '/methodology' | '/indicator/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IndicatorsRoute: typeof IndicatorsRoute
  MethodologyRoute: typeof MethodologyRoute
  IndicatorIdRoute: typeof IndicatorIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicators': {
      id: '/indicators'
      path: '/indicators'
      fullPath: '/indicators'
      preLoaderRoute: typeof IndicatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicator/$id': {
      id: '/indicator/$id'
      path: '/indicator/$id'
      fullPath: '/indicator/$id'
      preLoaderRoute: typeof IndicatorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IndicatorsRoute: IndicatorsRoute,
  MethodologyRoute: MethodologyRoute,
  IndicatorIdRoute: IndicatorIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
